// Minimal mirror of src/lib/integrations.ts — id + authType only, just enough to validate a
// connection request server-side. Duplicated rather than imported for the same reason as
// currency-rates.ts and lead-scoring.ts: Supabase deploys each edge function independently and
// doesn't bundle files outside supabase/functions/. If you add/remove an integration in
// src/lib/integrations.ts, mirror its id + authType here too.

export const INTEGRATIONS: { id: string; authType: "api_key" | "oauth" }[] = [
  { id: "openai", authType: "api_key" },
  { id: "anthropic", authType: "api_key" },
  { id: "google-gemini", authType: "api_key" },
  { id: "libooks", authType: "api_key" },
  { id: "sellia", authType: "api_key" },
  { id: "gmail", authType: "oauth" },
  { id: "outlook", authType: "oauth" },
  { id: "stripe", authType: "api_key" },
  { id: "flutterwave", authType: "api_key" },
  { id: "payunit", authType: "api_key" },
  { id: "paypal", authType: "oauth" },
  { id: "adyen", authType: "api_key" },
  { id: "mollie", authType: "api_key" },
  { id: "checkoutcom", authType: "api_key" },
  { id: "worldline", authType: "api_key" },
  { id: "nexi", authType: "api_key" },
  { id: "gocardless", authType: "oauth" },
  { id: "vivawallet", authType: "api_key" },
  { id: "revolut-business", authType: "oauth" },
  { id: "paystack", authType: "api_key" },
  { id: "mpesa", authType: "api_key" },
  { id: "interswitch", authType: "api_key" },
  { id: "dpo-group", authType: "api_key" },
  { id: "cellulant", authType: "api_key" },
  { id: "fawry", authType: "api_key" },
  { id: "payfast", authType: "api_key" },
  { id: "peach-payments", authType: "api_key" },
  { id: "campay", authType: "api_key" },
  { id: "cinetpay", authType: "api_key" },
  { id: "kkiapay", authType: "api_key" },
  { id: "wave", authType: "api_key" },
  { id: "orange-money", authType: "api_key" },
  { id: "mtn-momo", authType: "api_key" },
  { id: "chapa", authType: "api_key" },
  { id: "semoa", authType: "api_key" },
  { id: "maxicash", authType: "api_key" },
  { id: "slack", authType: "oauth" },
  { id: "whatsapp", authType: "api_key" },
  { id: "telegram", authType: "api_key" },
  { id: "messenger", authType: "oauth" },
  { id: "instagram-dm", authType: "oauth" },
  { id: "zoom", authType: "api_key" },
  { id: "google-meet", authType: "oauth" },
  { id: "microsoft-teams", authType: "oauth" },
  { id: "calendly", authType: "api_key" },
  { id: "google-calendar", authType: "oauth" },
  { id: "twilio", authType: "api_key" },
  { id: "aircall", authType: "api_key" },
  { id: "shopify", authType: "oauth" },
  { id: "woocommerce", authType: "api_key" },
  { id: "prestashop", authType: "api_key" },
  { id: "bigcommerce", authType: "api_key" },
  { id: "quickbooks", authType: "oauth" },
  { id: "xero", authType: "oauth" },
  { id: "sage", authType: "api_key" },
  { id: "zendesk", authType: "oauth" },
  { id: "intercom", authType: "oauth" },
  { id: "freshdesk", authType: "api_key" },
  { id: "mailchimp", authType: "api_key" },
  { id: "meta-ads", authType: "oauth" },
  { id: "google-ads", authType: "oauth" },
  { id: "linkedin-ads", authType: "oauth" },
  { id: "zapier", authType: "api_key" },
  { id: "make", authType: "api_key" },
  { id: "n8n", authType: "api_key" },
  { id: "pipedream", authType: "api_key" },
  { id: "google-drive", authType: "oauth" },
  { id: "dropbox", authType: "oauth" },
  { id: "docusign", authType: "oauth" },
  { id: "notion", authType: "oauth" },
  { id: "asana", authType: "oauth" },
  { id: "trello", authType: "oauth" },
];
