import { createContext, useContext, useEffect, useState, type ReactNode } from 'react';

export type Lang = 'fr' | 'en';

export const translations: Record<Lang, Record<string, string>> = {
  fr: {
    // Header / nav
    'nav.features': 'Fonctionnalités',
    'nav.pricing': 'Tarifs',
    'nav.faq': 'FAQ',
    'nav.contact': 'Contact',
    'nav.login': 'Connexion',
    'nav.signup': 'Essai gratuit',
    'nav.startFree': 'Commencer gratuitement',
    'nav.seePricing': 'Voir les tarifs',
    'nav.search': 'Rechercher…',
    'nav.security': 'Sécurité',
    'nav.superAdmin': 'Super Admin',
    'nav.logout': 'Déconnexion',
    // Sidebar groups
    'group.crm': 'CRM',
    'group.insights': 'Analyses',
    'group.system': 'Système',
    'group.admin': 'Administration',
    // Sidebar labels
    'mod.dashboard': 'Dashboard',
    'mod.pipeline': 'Pipeline',
    'mod.contacts': 'Contacts',
    'mod.companies': 'Companies',
    'mod.activities': 'Activités',
    'mod.tasks': 'Tâches',
    'mod.calendar': 'Calendrier',
    'mod.forecast': 'Forecast',
    'mod.reports': 'Rapports',
    'mod.import_export': 'Import/Export',
    'mod.documents': 'Documents',
    'mod.automations': 'Automatisations',
    'mod.notifications': 'Notifications',
    'mod.security': 'Sécurité',
    'mod.billing': 'Facturation',
    'mod.team': 'Équipe & Rôles',
    'mod.admin': 'Espace Admin',
    'mod.super_admin': 'Super Admin',
    'mod.ai_assistant': 'Assistant IA',
    // Common
    'common.loading': 'Chargement…',
    'common.profileLoading': 'Profil en cours de chargement…',
    'common.plan': 'Plan',
    'common.trial': 'Essai',
    'common.daysLeft': 'j restants',
    'common.unlock': 'Débloquer avec',
    'common.popular': 'Le plus populaire',
    'common.perMonth': '/mois',
    'common.monthly': 'Mensuel',
    'common.annual': 'Annuel',
    'common.free': 'gratuit',
    'common.users': 'utilisateurs',
    'common.unlimited': 'Illimité',
    'common.upTo': "Jusqu'à",
    'common.exportCsv': 'Export CSV',
    'common.allCountries': 'Tous les pays',
    'common.noData': 'Aucune donnée',
    'common.save': 'Enregistrer',
    'common.cancel': 'Annuler',
    'common.delete': 'Supprimer',
    'common.edit': 'Modifier',
    'common.create': 'Créer',
    'common.close': 'Fermer',
    'common.confirm': 'Confirmer',
    'common.search': 'Rechercher',
    'common.actions': 'Actions',
    'common.status': 'Statut',
    'common.name': 'Nom',
    'common.email': 'Email',
    'common.phone': 'Téléphone',
    'common.company': 'Entreprise',
    'common.country': 'Pays',
    'common.city': 'Ville',
    'common.currency': 'Devise',
    'common.created': 'Créé le',
    'common.required': 'Ce champ est requis',
    'common.optional': 'optionnel',
    // Landing hero
    'landing.badge': '190+ pays · Multi-devise · Mobile Money',
    'landing.heroTitle1': 'Le CRM international qui propulse',
    'landing.heroTitle2': 'vos ventes, partout',
    'landing.heroSubtitle': 'centralise votre pipeline, vos contacts, vos rapports — avec isolation multi-tenant stricte, devises internationales et Mobile Money là où ça compte. Pensé pour scaler à l\'échelle mondiale, dès aujourd\'hui.',
    'landing.trialDays': '7 jours d\'essai',
    'landing.noCard': 'Sans carte',
    'landing.multiTenant': 'Multi-tenant',
    // Features
    'landing.featuresTitle': 'Tout ce dont votre équipe commerciale a besoin',
    'landing.featuresSubtitle': 'Des modules complets, activés dès le premier jour, conçus pour les entreprises internationales.',
    'landing.feature1.title': 'Pipeline visuel',
    'landing.feature1.desc': 'Deals par étapes, montants, devises, dates de clôture. Glissez-déposez.',
    'landing.feature2.title': 'Contacts & Companies',
    'landing.feature2.desc': 'Base unifiée, scopée par tenant, rattachée aux deals et activités.',
    'landing.feature3.title': 'Forecast & Rapports',
    'landing.feature3.desc': 'Prévisions de revenus, conversion par étape, exports CSV.',
    'landing.feature4.title': 'Automatisations',
    'landing.feature4.desc': 'Déclencheurs et actions sans code. Rôles personnalisés par module.',
    'landing.feature5.title': 'Multi-devise & Mobile Money',
    'landing.feature5.desc': 'USD, EUR, GBP, AED, XOF, NGN, KES… + Orange, MTN, Wave, M-Pesa selon pays.',
    'landing.feature6.title': 'Isolation multi-tenant',
    'landing.feature6.desc': 'Row-Level Security. Aucune fuite entre entreprises, même par URL.',
    // Pricing
    'landing.pricingTitle': 'Des forfaits simples, transparents',
    'landing.pricingSubtitle': '7 jours d\'essai gratuit sur tous les plans. Sans carte bancaire.',
    'landing.tryFree': 'Essayer gratuitement',
    // Testimonials
    'landing.testimonialsTitle': 'Ils nous font confiance',
    // FAQ
    'landing.faqTitle': 'FAQ',
    // Footer
    'footer.tagline': 'La plateforme CRM SaaS multi-tenant internationale. Éditée par',
    'footer.product': 'Produit',
    'footer.legal': 'Légal',
    'footer.contact': 'Contact',
    'footer.cgu': 'CGU',
    'footer.privacy': 'Confidentialité',
    'footer.terms': 'Mentions légales',
    'footer.about': 'À propos',
    'footer.cookies': 'Gérer mes cookies',
    'footer.rights': 'Tous droits réservés.',
    'footer.locations': 'Dubaï · Yaoundé/Soa',
    // Auth
    'auth.loginTitle': 'Connexion à votre compte',
    'auth.loginSubtitle': 'Accédez à votre CRM',
    'auth.signupTitle': 'Créer votre compte',
    'auth.signupSubtitle': 'Démarrez votre essai gratuit de 7 jours',
    'auth.email': 'Adresse email',
    'auth.password': 'Mot de passe',
    'auth.fullName': 'Nom complet',
    'auth.companyName': 'Nom de l\'entreprise',
    'auth.loginBtn': 'Se connecter',
    'auth.signupBtn': 'Créer mon compte',
    'auth.noAccount': 'Pas encore de compte ?',
    'auth.haveAccount': 'Déjà un compte ?',
    'auth.createAccount': 'Créer un compte',
    'auth.signin': 'Se connecter',
    'auth.or': 'ou',
    // Onboarding
    'onboarding.location': 'Localisation',
    'onboarding.currency': 'Devise',
    'onboarding.plan': 'Forfait',
    'onboarding.comCode': 'Code commercial',
    'onboarding.companyName': 'Nom de l\'entreprise',
    'onboarding.country': 'Pays',
    'onboarding.region': 'Région / Province',
    'onboarding.city': 'Ville',
    'onboarding.chooseCurrency': 'Choisissez votre devise',
    'onboarding.currencyHint': 'Cette devise sera cohérente dans tout votre compte : rapports, factures, dashboards, exports.',
    'onboarding.choosePlan': 'Choisissez votre forfait',
    'onboarding.planHint': '7 jours d\'essai gratuit. Sans carte bancaire. Modifiable à tout moment.',
    'onboarding.comCodeTitle': 'Code commercial',
    'onboarding.comCodeHint': 'Laissez vide si vous n\'en avez pas. Ce champ n\'est jamais requis.',
    'onboarding.comCodePlaceholder': 'Laissez vide si vous n\'en avez pas',
    'onboarding.codeValid': 'Code valide',
    'onboarding.codeInvalid': 'Code non reconnu. Vous pouvez continuer sans code.',
    'onboarding.summary': 'Récapitulatif',
    'onboarding.trialLabel': 'Essai',
    'onboarding.trialValue': '7 jours gratuits',
    'onboarding.startTrial': 'Démarrer mon essai',
    'onboarding.back': 'Retour',
    'onboarding.continue': 'Continuer',
    'onboarding.configuring': 'Configuration…',
    'onboarding.timezone': 'Fuseau horaire',
    'onboarding.dial': 'Indicatif',
    'onboarding.recommended': 'Recommandé pour votre pays',
    // Super Admin dashboard
    'sa.title': 'Super Admin',
    'sa.subtitle': 'Vue transverse sur tous les tenants',
    'sa.tenants': 'Tenants',
    'sa.users': 'Utilisateurs',
    'sa.mrr': 'MRR (USD)',
    'sa.sales': 'Ventes tracées',
    'sa.byPlan': 'Répartition par forfait',
    'sa.topCountries': 'Top pays',
    'sa.recentTenants': 'Tenants récents',
    'sa.company': 'Entreprise',
    // Cookie banner
    'cookie.text': 'Nous utilisons des cookies pour améliorer votre expérience. Vous pouvez accepter ou personnaliser vos préférences.',
    'cookie.accept': 'Accepter',
    'cookie.reject': 'Refuser',
    'cookie.customize': 'Personnaliser',
  },
  en: {
    'nav.features': 'Features',
    'nav.pricing': 'Pricing',
    'nav.faq': 'FAQ',
    'nav.contact': 'Contact',
    'nav.login': 'Sign in',
    'nav.signup': 'Free trial',
    'nav.startFree': 'Start for free',
    'nav.seePricing': 'See pricing',
    'nav.search': 'Search…',
    'nav.security': 'Security',
    'nav.superAdmin': 'Super Admin',
    'nav.logout': 'Sign out',
    'group.crm': 'CRM',
    'group.insights': 'Insights',
    'group.system': 'System',
    'group.admin': 'Administration',
    'mod.dashboard': 'Dashboard',
    'mod.pipeline': 'Pipeline',
    'mod.contacts': 'Contacts',
    'mod.companies': 'Companies',
    'mod.activities': 'Activities',
    'mod.tasks': 'Tasks',
    'mod.calendar': 'Calendar',
    'mod.forecast': 'Forecast',
    'mod.reports': 'Reports',
    'mod.import_export': 'Import/Export',
    'mod.documents': 'Documents',
    'mod.automations': 'Automations',
    'mod.notifications': 'Notifications',
    'mod.security': 'Security',
    'mod.billing': 'Billing',
    'mod.team': 'Team & Roles',
    'mod.admin': 'Admin Space',
    'mod.super_admin': 'Super Admin',
    'mod.ai_assistant': 'AI Assistant',
    'common.loading': 'Loading…',
    'common.profileLoading': 'Loading profile…',
    'common.plan': 'Plan',
    'common.trial': 'Trial',
    'common.daysLeft': 'days left',
    'common.unlock': 'Unlock with',
    'common.popular': 'Most popular',
    'common.perMonth': '/mo',
    'common.monthly': 'Monthly',
    'common.annual': 'Annual',
    'common.free': 'free',
    'common.users': 'users',
    'common.unlimited': 'Unlimited',
    'common.upTo': 'Up to',
    'common.exportCsv': 'Export CSV',
    'common.allCountries': 'All countries',
    'common.noData': 'No data',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.create': 'Create',
    'common.close': 'Close',
    'common.confirm': 'Confirm',
    'common.search': 'Search',
    'common.actions': 'Actions',
    'common.status': 'Status',
    'common.name': 'Name',
    'common.email': 'Email',
    'common.phone': 'Phone',
    'common.company': 'Company',
    'common.country': 'Country',
    'common.city': 'City',
    'common.currency': 'Currency',
    'common.created': 'Created',
    'common.required': 'This field is required',
    'common.optional': 'optional',
    'landing.badge': '190+ countries · Multi-currency · Mobile Money',
    'landing.heroTitle1': 'The international CRM that drives',
    'landing.heroTitle2': 'your sales, everywhere',
    'landing.heroSubtitle': 'centralizes your pipeline, contacts, reports — with strict multi-tenant isolation, international currencies and Mobile Money where it matters. Built to scale globally, from day one.',
    'landing.trialDays': '7-day trial',
    'landing.noCard': 'No card required',
    'landing.multiTenant': 'Multi-tenant',
    'landing.featuresTitle': 'Everything your sales team needs',
    'landing.featuresSubtitle': 'Complete modules, activated from day one, built for international businesses.',
    'landing.feature1.title': 'Visual Pipeline',
    'landing.feature1.desc': 'Deals by stage, amounts, currencies, close dates. Drag and drop.',
    'landing.feature2.title': 'Contacts & Companies',
    'landing.feature2.desc': 'Unified database, tenant-scoped, linked to deals and activities.',
    'landing.feature3.title': 'Forecast & Reports',
    'landing.feature3.desc': 'Revenue forecasts, stage conversion, CSV exports.',
    'landing.feature4.title': 'Automations',
    'landing.feature4.desc': 'Triggers and actions, no code. Custom roles per module.',
    'landing.feature5.title': 'Multi-currency & Mobile Money',
    'landing.feature5.desc': 'USD, EUR, GBP, AED, XOF, NGN, KES… + Orange, MTN, Wave, M-Pesa by country.',
    'landing.feature6.title': 'Multi-tenant isolation',
    'landing.feature6.desc': 'Row-Level Security. No data leaks between companies, even by URL.',
    'landing.pricingTitle': 'Simple, transparent plans',
    'landing.pricingSubtitle': '7-day free trial on all plans. No credit card required.',
    'landing.tryFree': 'Try for free',
    'landing.testimonialsTitle': 'Trusted by',
    'landing.faqTitle': 'FAQ',
    'footer.tagline': 'The international multi-tenant SaaS CRM platform. Published by',
    'footer.product': 'Product',
    'footer.legal': 'Legal',
    'footer.contact': 'Contact',
    'footer.cgu': 'Terms of Use',
    'footer.privacy': 'Privacy',
    'footer.terms': 'Legal Notice',
    'footer.about': 'About',
    'footer.cookies': 'Manage cookies',
    'footer.rights': 'All rights reserved.',
    'footer.locations': 'Dubai · Yaoundé/Soa',
    'auth.loginTitle': 'Sign in to your account',
    'auth.loginSubtitle': 'Access your CRM',
    'auth.signupTitle': 'Create your account',
    'auth.signupSubtitle': 'Start your 7-day free trial',
    'auth.email': 'Email address',
    'auth.password': 'Password',
    'auth.fullName': 'Full name',
    'auth.companyName': 'Company name',
    'auth.loginBtn': 'Sign in',
    'auth.signupBtn': 'Create my account',
    'auth.noAccount': 'No account yet?',
    'auth.haveAccount': 'Already have an account?',
    'auth.createAccount': 'Create account',
    'auth.signin': 'Sign in',
    'auth.or': 'or',
    'onboarding.location': 'Location',
    'onboarding.currency': 'Currency',
    'onboarding.plan': 'Plan',
    'onboarding.comCode': 'Commercial code',
    'onboarding.companyName': 'Company name',
    'onboarding.country': 'Country',
    'onboarding.region': 'Region / Province',
    'onboarding.city': 'City',
    'onboarding.chooseCurrency': 'Choose your currency',
    'onboarding.currencyHint': 'This currency will be consistent across your account: reports, invoices, dashboards, exports.',
    'onboarding.choosePlan': 'Choose your plan',
    'onboarding.planHint': '7-day free trial. No credit card. Changeable at any time.',
    'onboarding.comCodeTitle': 'Commercial code',
    'onboarding.comCodeHint': 'Leave empty if you don\'t have one. This field is never required.',
    'onboarding.comCodePlaceholder': 'Leave empty if you don\'t have one',
    'onboarding.codeValid': 'Valid code',
    'onboarding.codeInvalid': 'Code not recognized. You can continue without a code.',
    'onboarding.summary': 'Summary',
    'onboarding.trialLabel': 'Trial',
    'onboarding.trialValue': '7 days free',
    'onboarding.startTrial': 'Start my trial',
    'onboarding.back': 'Back',
    'onboarding.continue': 'Continue',
    'onboarding.configuring': 'Setting up…',
    'onboarding.timezone': 'Timezone',
    'onboarding.dial': 'Dial code',
    'onboarding.recommended': 'Recommended for your country',
    'sa.title': 'Super Admin',
    'sa.subtitle': 'Cross-tenant overview',
    'sa.tenants': 'Tenants',
    'sa.users': 'Users',
    'sa.mrr': 'MRR (USD)',
    'sa.sales': 'Tracked sales',
    'sa.byPlan': 'Distribution by plan',
    'sa.topCountries': 'Top countries',
    'sa.recentTenants': 'Recent tenants',
    'sa.company': 'Company',
    'cookie.text': 'We use cookies to improve your experience. You can accept or customize your preferences.',
    'cookie.accept': 'Accept',
    'cookie.reject': 'Reject',
    'cookie.customize': 'Customize',
  },
};

interface LanguageContextValue {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextValue>({
  lang: 'fr',
  setLang: () => {},
  t: (k: string) => k,
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>(() => {
    if (typeof window === 'undefined') return 'fr';
    return (localStorage.getItem('liafrik-lang') as Lang) || 'fr';
  });

  const setLang = (l: Lang) => {
    setLangState(l);
    localStorage.setItem('liafrik-lang', l);
    document.documentElement.lang = l;
  };

  useEffect(() => {
    document.documentElement.lang = lang;
  }, [lang]);

  const t = (key: string): string => {
    return translations[lang][key] || translations.fr[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
